FROM alpine:latest

#directorio de trabajo de la imagen
WORKDIR /app


COPY mensaje.txt /mensaje.txt

COPY app .
#el punto indica que se copia todo el contenido del directorio app al directorio de trabajo de la imagen osea al workdir /app